### PR TITLE
fix: updatetimestamp refeshed unexpectedly

### LINKED ISSUE #381: worker's updatetime refreshed unexpectedly

### PR DESCRIPTION
**Pull request by bjwswang**
#### Which issue(s) this PR fixes

Fixes #381

### CODE REVIEW

File: api/base/v1alpha1/worker.go [hunk 1]
```diff
@@ -68,17 +68,32 @@ func (worker Worker) MakeRegistrationModelName() string {
...
 
 func (worker Worker) PendingCondition() Condition {
+	currCon := worker.Status.GetCondition(TypeReady)
+	// return current condition if condition not changed
+	if currCon.Status == corev1.ConditionFalse && currCon.Reason == "Pending" {
+		return currCon
+	}
+	// keep original LastSuccessfulTime if have
+	lastSuccessfulTime := metav1.Now()
+	if currCon.LastSuccessfulTime.String() != "" {
```
Comment (Abirdcfly) [inline api/base/v1alpha1/worker.go:78]: use `.IsZero()` maybe better

File: api/base/v1alpha1/worker.go [hunk 2]
```diff
@@ -90,13 +105,23 @@ func (worker Worker) ReadyCondition() Condition {
 }
 
 func (worker Worker) ErrorCondition(msg string) Condition {
+	currCon := worker.Status.GetCondition(TypeReady)
+	// return current condition if condition not changed
+	if currCon.Status == corev1.ConditionFalse && currCon.Reason == "Error" {
+		return currCon
```
Comment (Abirdcfly) [inline api/base/v1alpha1/worker.go:111]: I guess should also update `Message` filed.

File: controllers/worker_controller.go [hunk 3]
```diff
@@ -73,60 +73,61 @@ type WorkerReconciler struct {
 func (r *WorkerReconciler) Reconcile(ctx context.Context, req ctrl.Request) (result ctrl.Result, err error) {
 	log := ctrl.LoggerFrom(ctx)
 	log.V(5).Info("Start Worker Reconcile")
+	log.V(5).Info("Get Worker instance")
```
Comment (Abirdcfly) [inline controllers/worker_controller.go:76]: line 75 and line 76 only need one?

File: pkg/worker/worker.go [hunk 4]
```diff
@@ -339,6 +343,17 @@ func (worker *PodWorker) Start(ctx context.Context) error {
 	return nil
 }
 
+func MakeMergedDeployment(target *appsv1.Deployment, desired *appsv1.Deployment) *appsv1.Deployment {
+	merged := target.DeepCopy()
+
+	// merge this deployment with desired
+	merged.Spec.Template.Spec.InitContainers = desired.Spec.Template.Spec.InitContainers
```
Comment (Abirdcfly) [inline pkg/worker/worker.go:350]: What about just replace `Spec.Template.Spec`?

**Review by Abirdcfly — APPROVED** [review]
