### PR TITLE
fix: correct the totalCount value returned by the listModels API

### LINKED ISSUE #484: The interface returned an incorrect totalCount value after keyword search on the model warehouse list page
模型仓库列表页关键字搜索后接口返回的totalCount值错误

### PR DESCRIPTION
**Pull request by dayuy**
#### What type of PR is this?
/kind bug

#### What this PR does / why we need it
correct the totalCount value returned by the listModels API
#### Which issue(s) this PR fixes

Fixes #484

### CODE REVIEW

File: apiserver/pkg/model/model.go [hunk 1]
```diff
@@ -229,40 +229,25 @@ func ListModels(ctx context.Context, c dynamic.Interface, input generated.ListMo
...
 		result = append(result, m)
-
-		// break if page size matches
-		if len(result) == pageSize {
-			break
-		}
 	}
-
+	totalCount := len(result)
+	pageStart := (page - 1) * pageSize
```
Comment (0xff-dev) [inline apiserver/pkg/model/model.go:242]: Should also check if `pageStart` exceeds `totalCount`.

**Review by 0xff-dev — APPROVED** [review]

**Review by Abirdcfly — APPROVED** [review]
There may be several places in the code that are written like this. Do you want to modify them all in the current pr?

**Comment by dayuy** [comment]
> There may be several places in the code that are written like this. Do you want to modify them all in the current pr?

sure, I will do it tomorrow
