### PR TITLE
fix: too long to call listModelServices

### LINKED ISSUE #537: it takes too long to call listModelServices

### PR DESCRIPTION
**Pull request by 0xff-dev**
#### What type of PR is this?
/kind bug

#### What this PR does / why we need it
fix: too long to call listModelServices

#### Which issue(s) this PR fixes

Fix #537

### CODE REVIEW

File: apiserver/pkg/modelservice/helper.go [hunk 1]
```diff
@@ -80,3 +81,28 @@ func LLM2ModelService(llm *generated.Llm) *generated.ModelService {
...
+		Types:             new(string),
+		APIType:           new(string),
+		EmbeddingModels:   []string{*worker.ID},
+		LlmModels:         []string{*worker.ID},
+		Status:            worker.Status,
+		Message:           worker.Message,
+	}
+
+	*ms.ProviderType = "worker"
+	*ms.Types = common.ModelTypeAll
```
Comment (bjwswang) [inline apiserver/pkg/modelservice/helper.go:105]: This depends on the worker's model type

Comment (0xff-dev) [reply apiserver/pkg/modelservice/helper.go]: Done.

**Review by bjwswang — APPROVED** [review]
LGTM
